# This is a GitHub Workflow configuration
# Sytnax reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Build Resume Files
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    #    Check to make sure the commit doesn't contain "ci-skip"
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Initialize NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build Website
        run: .github/scripts/buildWebsite.sh

      - name: Build PDF
        run: .github/scripts/buildPDF.sh

      - name: Commit & Push Changes
        run: |
          if [[ `git status --porcelain` ]]; then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add index.html
              git add Nellis-Resume.pdf
              git commit -am "[ci-skip] Push changes"
              git push
          fi
