# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Resume File
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    #    Check to make sure the commit doesn't contain "ci-skip"
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Initialize NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build index.html
        run: .github/scripts/build.sh

      - name: Commit & Push Changes
        run: |
          if [[ `git status --porcelain` ]]; then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add index.html
              git commit -am "[ci-skip] Push changes"
              git push
          fi
